# Generated by Django 5.2.8 on 2025-11-13 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasia'), ('scifi', 'Ficção Científica'), ('horror', 'Terror'), ('mystery', 'Mistério'), ('adventure', 'Aventura')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='adventures/covers/')),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=6)),
                ('estimated_duration', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aventura',
                'verbose_name_plural': 'Aventuras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='adventures.adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-last_played'],
            },
        ),
    ]
