# Generated by Django 5.2.8 on 2025-11-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaviate_class_name', models.CharField(db_index=True, help_text='Nome da classe no Weaviate', max_length=255, unique=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_size_bytes', models.BigIntegerField(default=0)),
                ('chunks_extracted', models.IntegerField(default=0)),
                ('chunks_indexed', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('partial', 'Parcial'), ('error', 'Erro')], db_index=True, default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_book', to='adventures.adventure')),
            ],
            options={
                'verbose_name': 'Processed Book',
                'verbose_name_plural': 'Processed Books',
                'db_table': 'game_processed_books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(db_index=True, default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado em USD', max_digits=10)),
                ('operation_type', models.CharField(choices=[('narrate', 'Narrativa'), ('combat', 'Combate'), ('test', 'Teste'), ('dialogue', 'Diálogo'), ('exploration', 'Exploração'), ('other', 'Outro')], db_index=True, default='other', max_length=50)),
                ('model_name', models.CharField(db_index=True, default='gemini-pro', max_length=100)),
                ('response_time_ms', models.IntegerField(default=0, help_text='Tempo de resposta em milissegundos')),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage', to='adventures.adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usage Records',
                'db_table': 'game_api_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='game_api_us_user_id_20ff3d_idx'), models.Index(fields=['adventure', 'created_at'], name='game_api_us_adventu_b6321f_idx'), models.Index(fields=['created_at', 'success'], name='game_api_us_created_8d7730_idx'), models.Index(fields=['user', 'operation_type', 'created_at'], name='game_api_us_user_id_40249d_idx')],
            },
        ),
    ]
